name: Deploy Next.js App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test # Or your specific test command

    - name: Build Next.js App
      run: npm run build

  